ALTER TABLE resumes ADD COLUMN created_at INTEGER NOT NULL DEFAULT 0;
ALTER TABLE resumes ADD COLUMN export_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE resumes ADD COLUMN is_public INTEGER NOT NULL DEFAULT 0;
ALTER TABLE resumes ADD COLUMN view_num INTEGER NOT NULL DEFAULT 0;
UPDATE resumes SET created_at = updated_at WHERE created_at = 0;
