// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/**:route': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/[...route]').default>>>>
    }
    '/api/ai/**:route': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai/[...route]').default>>>>
    }
    '/api/comment/**:route': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/comment/[...route]').default>>>>
    }
    '/api/comments/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/comments/query').default>>>>
    }
    '/api/engagement/**:route': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/engagement/[...route]').default>>>>
    }
    '/api/export/**:route': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/export/[...route]').default>>>>
    }
    '/api/favorite/**:route': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/favorite/[...route]').default>>>>
    }
    '/api/feedback/**:route': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/feedback/[...route]').default>>>>
    }
    '/api/import/**:route': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/import/[...route]').default>>>>
    }
    '/api/invite/**:route': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/invite/[...route]').default>>>>
    }
    '/api/job/**:route': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/job/[...route]').default>>>>
    }
    '/api/mianjing/**:route': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mianjing/[...route]').default>>>>
    }
    '/api/notification/**:route': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notification/[...route]').default>>>>
    }
    '/api/order/**:route': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/order/[...route]').default>>>>
    }
    '/api/post/**:route': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/post/[...route]').default>>>>
    }
    '/api/progress/**:route': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/progress/[...route]').default>>>>
    }
    '/api/resume/**:route': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/resume/[...route]').default>>>>
    }
    '/api/schools': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/schools').default>>>>
    }
    '/api/share/**:route': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/share/[...route]').default>>>>
    }
    '/api/template/hidden': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/template/hidden').default>>>>
    }
    '/api/template/stats': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/template/stats').default>>>>
    }
    '/api/translate': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/translate').default>>>>
    }
    '/api/upload/**:route': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload/[...route].get').default>>>>
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload/[...route].options').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload/[...route].post').default>>>>
    }
    '/export': {
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/export.options').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/export.post').default>>>>
    }
    '/gitee': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/gitee').default>>>>
    }
    '/mcp': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/mcp').default>>>>
    }
    '/mcp/messages': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/mcp/messages').default>>>>
    }
    '/user/**:route': {
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/user/[...route].options').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/user/[...route].post').default>>>>
    }
    '/user/info': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/user/info.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}